title: Garbaz' Blog
author:
  name: Garbaz
  email: garbaz@t-online.de
#description: A made up language
# header_pages:
#   - ideas.md
remote_theme: jekyll/minima@41b97699af658128fa9983e5312ca5516641f335
minima:
  skin: dark
  date_format: "%Y-%m-%d"
  social_links:
    github: "Garbaz"
    discord: "Garbaz#2585"


plugins:
  - jekyll-feed
  - jekyll-sitemap
  # - jekyll-gist
  # - jekyll-paginate
  # - jekyll-remote-theme
  # - jekyll-scholar

# kramdown:
#   math_engine: katex
#   math_engine_opts:
#     output: mathml

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - 
    scope:
      path: ""
      type: posts
    values:
      tags: [Other]


